---
- name: Install docker
  become: true
  shell: amazon-linux-extras install -y docker

- name: Start docker service
  become: true
  service:
    name: docker
    enabled: true
    state: started

- name: Add user to Docker
  user:
    name: ec2-user
    group: docker

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose

- name: Symlink
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link
    owner: ec2-user
    mode: '0755'

- name: Install vue2048 docker-compose yaml
  copy:
    src: /home/sinensia/vue2048-main/docker-compose.yml
    dest: /home/ec2-user/Docker/

- name: Pull package from Dockerhub
  become: true
  shell: docker-compose -f /home/ec2-user/Docker/docker-compose.yml pull

- name: Run docker-compose
  become: true
  shell: docker-compose -f /home/ec2-user/Docker/docker-compose.yml up -d --no-build
