---
- hosts: aws-instance
  become: true
  tasks:
    - name: Install apache2 httpd
      yum:
        name: httpd
        state: latest

  # - name: Install git
  #   yum:
  #     name: git
  #     state: latest

    - name: Start apache2 service
      service:
        name: httpd
        state: started

    - name: Git vue-2048
      copy:
        src: /home/sinensia/vue2048-main/dist/
        dest: /var/www/html/
